# Generated by Django 3.0.6 on 2020-07-07 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='id',
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_name',
            field=models.CharField(choices=[('IT Fondamental', 'IT Fondamental'), ('CS Fondamental', 'CS Fondamental'), ('Mathematics_1', 'Mathematics_1'), ('Discrete Mathematics', 'Discrete Mathematics'), ('C++ Programming', 'C++ Programming'), ('Java Programming', 'Java Programming'), ('Python Programming', 'Python Programming'), ('C++ Advanced', 'C++ Advanced'), ('Java Advanced', 'Java Advanced'), ('Python Advanced', 'Python Advanced')], default='Mathematics_1', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='instructor_courses',
            name='number_off_student',
            field=models.IntegerField(default='100'),
        ),
        migrations.CreateModel(
            name='Student_Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_date', models.DateField(auto_now_add=True)),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='userprofile.Instructor_Courses')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='userprofile.Student_Info')),
            ],
        ),
    ]
