# Generated by Django 3.0.6 on 2020-07-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20200707_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor_courses',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='instructor_courses',
            name='start_date',
            field=models.DateField(),
        ),
    ]
